import { Router } from "express";
import products from "./products.js";
import auth from "./auth.js";
import admin from "./admin.js";
import looks from "./looks.js";
import wardrobe from "./wardrobe.js";
import userImages from "./userImages.js";
import generate from "./generate.js";
import profile from "./profile.js";
import fashionContent from "./fashionContent.js";
import conversations from "./conversations.js";
import cron from "./cron.js";
import search from "./search.js";
import styleReport from "./styleReport.js";
import microstores from "./microstores.js";
import brands from "./brands.js";
import wishlist from "./wishlist.js";
import brand from "./brand.js";
import cart from "./cart.js";
import recommendations from "./recommendations.js";
import analytics from "./analytics.js";
import feedPosts from "./feedPosts.js";
import user from "./user.js";
import lookPlanning from "./lookPlanning.js";
import landing from "./landing.js";

const router = Router();
router.use("/products", products);
router.use("/search", search);
router.use("/style-report", styleReport);
router.use("/auth", auth);
router.use("/admin", admin);
router.use("/looks", looks);
router.use("/wardrobe", wardrobe);
router.use("/user-images", userImages);
router.use("/generate", generate);
router.use("/profile", profile);
router.use("/fashion-content", fashionContent);
router.use("/conversations", conversations);
router.use("/cron", cron);
router.use("/microstores", microstores);
router.use("/brands", brands);
router.use("/wishlist", wishlist);
router.use("/brand", brand);
router.use("/cart", cart);
router.use("/recommendations", recommendations);
router.use("/analytics", analytics);
router.use("/feed-posts", feedPosts);
router.use("/user", user);
router.use("/look-planning", lookPlanning);
router.use("/landing", landing);

export default router;
